#!/bin/bash
# Created by: Matthew Davidson
# Date 03/26/2017
# Purpose: Convenient command line tool to retrieve current weather

# Requires:
# API key from wunderground.com
# The xmllint package.

#Set varaibles:
tmpfile="/tmp/weather.xml"
# We need to extract data from the XML file that we download.
# We want the location, time, and several conditions, but there are others
# that we could also pull.
declare -a weather
weather=('full' 'observation_time' 'weather' 'temp_f' 'wind_dir' 'wind_mph' 'windchill_f' 'relative_humidity' 'pressure_in' 'pressure_trend')

#Declare an array to hold the current conditons.
declare -a conditions
conditions=()

#Pull fresh weather data:
# Add your API key and change to your location.
curl -s http://api.wunderground.com/api/xxxxxxxxxxxxxxxxxxxxxx/conditions/q/KY/Midway.xml > ${tmpfile}

#Grab the current conditions:
for i in "${weather[@]}"
do
	w=`xmllint --xpath 'string(//'$i')' ${tmpfile}`
	conditions+=("$w")
done

#Now echo array as the current weather.
echo "Forecast for: ${conditions[0]}"
echo ${conditions[1]}
echo "Current conditions: ${conditions[2]}"
echo "Current temperature is: ${conditions[3]} F"
echo "The wind is from the ${conditions[4]} at ${conditions[5]} with a wind chill of ${conditions[6]} F"
echo "Relative Humidity is ${conditions[7]}"
echo "The barometric pressure is: ${conditions[8]}"
echo "Pressure trending (+/-): ${conditions[9]}"

#echo "Send output to CSV for historical records."
(IFS=,; echo "${conditions[*]}") | sed -e "s/KY\,//" | sed -e "s/Last\ Updated\ on\ //" | sed -e "s/\, /,/g" >> /home/$USER/bin/weather_results.csv
rm ${tmpfile}
